color_list1=set(["white","Black","Red"])
color_list2=set(["Red","Green"])
print("Original set elements")
print(color_list1)
print(color_list2)
print("\n Difference of color_list1 and color_list2")
print(color_list1-color_list2)
print("\n Difference of color_list2 and color_list1")
print(color_list2-color_list1)
