num1=input('enter first number: ')
num2=input('enter second number:')
sum=int(num1)+int(num2)
diff=int(num1)-int(num2)
mul=int(num1)*int(num2)
div=float(num1)/float(num2)
print('the sum is',sum)
print('the difference is',diff)
print('the product is',mul)
print('the divided is',div)
